version: '3.1'

services:
  db:
    image: 'postgres:10'
    container_name: 'db'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: coda2
    ports:
      - 5433:5433
    command: -p 5433

  library:
    image: 'coda2/library:latest'
    container_name: 'library-app'
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5433/coda2
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  app:
    image: 'coda2/libraryproxy:latest'
    container_name: 'libraryproxy-app'
    depends_on:
      - library
      - db
      - rabbitmq
    ports:
     - 8081:8081
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5433/coda2
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_PORT=5672
      - spring_rabbitmq_host=rabbitmq

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    hostname: rabbitmq
    environment:
       RABBITMQ_DEFAULT_USER: guest
       RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"

